# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Run Java Tests

on: 
  push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

permissions:
  contents: write
  checks: write

jobs:
  tests:
    name: Java Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Gradle Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build --info
        gradle-version: 7.5.1
        build-root-directory: ./backend
    #- name: Run Tests
    #  uses: gradle/gradle-build-action@v2
    #  with:
    #    arguments: test --info
    #    gradle-version: 7.5.1
    #    build-root-directory: ./backend
    - name: Test Coverage
      id: jacoco_reporter
      uses: PavanMudigonda/jacoco-reporter@v4.6
      with:
        coverage_results_path: 'backend/build/coverage/report.xml'
        coverage_report_name: 'Java Coverage'
        coverage_report_title: 'JaCoCo'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        skip_check_run: false
        publish_only_summary: true
     # Publish Coverage Job Summary  # Optional
    - name: Add Coverage Job Summary
      run: echo "${{ steps.jacoco_reporter.outputs.coverageSummary }}" >> $GITHUB_STEP_SUMMARY
          
      # uploads the coverage-report.md artifact  # Optional

    - name: Upload Code Coverage Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report-markdown
        path: ./backend/build/coverage/
        retention-days: 1 

    - name: Upload Logs
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: gradle-test-results
        path: ./backend/build/reports/tests/test/
        retention-days: 1
      
    - name: Upload debug.log
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: debug.log
        path: ./backend/debug.log
        retention-days: 1


